### ISSUE TITLE
Not installing under Windows 10

### ISSUE THREAD

**Issue by soldius** [jneidel/mangareader-dl#19]
Hi I have been trying to install this on my windows 10 64 bit machine after installing node.js but it keep throwing me the error:

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for mangareader-dl@0.5.0: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-07-24T00_31_29_857Z-debug.log

I was searching around and just wondering if this is Windows 10 compatible? Is there something I missed? Sorry i am not very familiar with javascript. Thanks ahead for the help.

**Comment by jneidel** [comment]
Thanks for your interest!

There is a reason why I have this badge in the readme though:

![](https://camo.githubusercontent.com/77619480febe05d9e412eb8a444a7ed4edefc4ae/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f57696e646f77732d6e6f74253230737570706f727465642d7265642e7376673f7374796c653d666c61742d737175617265)

Windows is and never will be supported. The error you are seeing is npm telling you that I blocked the app from installing on windows systems.

Why?
Because I don't like Windows and don't like doing tech support or testing for the Windows platform.

If you ever convert to linux, I'll gladly help you if you have any problems :smile:
