### ISSUE TITLE
Add mangarock.com

### ISSUE THREAD

**Issue by ghost** [jneidel/mangareader-dl#2]
Mangarock is the best, no watermark, and also the quality is high with the small file size (they use Webp image format)

**Comment by jneidel** [comment]
The problem with mangarock is that due to it being a single page application (same urls for all pages of a chapter) it is hard to scrape. I can't just download the html and parse out the image source, instead I'll need to interact with the javascript on the website and get it to load the specific page to then download the html snapshot of the current state of the site.
While that is certainly possible, I would need to build a whole new download process to only accommodate this site, which doesn't feel like it would be worth the effort.

**Comment by ghost** [comment]
i see! btw i found alternative solution for Mangarock https://github.com/MinusGix/MangarockDownloader
